@host=http://localhost:7070

### Login
POST {{host}}/auth/login

{
    "username": "username",
    "password": "password"
}

### Register
POST {{host}}/auth/register
Content-Type: application/json

{
    "username": "username",
    "password": "password"
}

### Logout
POST {{host}}/auth/logout

### Search
POST {{host}}/api/directory/search
Content-Type: application/json

{
    "query": "game",
    "page": 1
}

### Movie
GET {{host}}/api/directory/movie/80274

### Movie
GET {{host}}/api/directory/series/1399